### PR TITLE
Update to Django 2.2

### PR DESCRIPTION
**Pull request by rmader**
The fixtures currently fail with the following output:

```
venv/bin/python3 manage.py loaddata fixtures/site-dev.json
Installed 1 object(s) from 1 fixture(s)
venv/bin/python3 manage.py loaddata fixtures/users-dev.json
Traceback (most recent call last):
  File "/home/robert/git/a4-speakup/venv/lib64/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/robert/git/a4-speakup/venv/lib64/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 381, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: near "-": syntax error
```

I assume that is because of app-labels containing `a4-speakup`. So we should probably make it `a4_candy`, just like in product/a+

Waiting for the other work for today to finish.

### CODE REVIEW

**Comment by rmader** [comment]
This is ready for review now

**Comment by fuzzylogic2000** [comment]
This is the stack trace for the empty DB:
  Applying a4_candy_ideas.0002_update_content_type...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 247, in apply_migration
    migration_recorded = True
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 34, in __exit__
    self.connection.check_constraints()
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in check_constraints
    bad_value, referenced_table_name, referenced_column_name
django.db.utils.IntegrityError: The row in table 'wagtailcore_grouppagepermission' with primary key '1' has an invalid foreign key: wagtailcore_grouppagepermission.page_id contains a value '1' that does not have a corresponding value in wagtailcore_page__old.id.
make: *** [Makefile:34: install] Error 1

**Comment by fuzzylogic2000** [comment]
And for my existing DB, which I can't reproduce anymore (?)
```
Running migrations:
  Applying a4_candy_ideas.0002_update_content_type...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 247, in apply_migration
    migration_recorded = True
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 34, in __exit__
    self.connection.check_constraints()
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in check_constraints
    bad_value, referenced_table_name, referenced_column_name
django.db.utils.IntegrityError: The row in table 'a4projects_project_moderators' with primary key '1' has an invalid foreign key: a4projects_project_moderators.project_id contains a value '1' that does not have a corresponding value in a4projects_project__old.id.
make: *** [Makefile:34: install] Error 1
```

**Comment by rmader** [comment]
Jep, that's a sqlite bug :(

**Comment by rmader** [comment]
I'd say let's give it a go on dev and role back if it fails

**Comment by rmader** [comment]
All migrations went well on the dev server. Hope to see sqlite fixed soon :(

**Pull request merged**
